[pytest]
testpaths=service/auth_service/tests
pythonpath = .
env_override_existing_values = 1
env_files =
    ./service/auth_service/.test.env
markers =
    positive: mark a test as a positive test
    negative: mark a test as a negative test
    slow: mark slow tests