[pytest]
testpaths=test
pythonpath = . ../..
env_override_existing_values = 1
env_files =
    services/auth_service/.test.env
markers =
    positive: mark a test as a positive test
    negative: mark a test as a negative test
    slow: mark slow tests
