"""optional_fields

Revision ID: 291b48396d89
Revises: bb8f6e2a1c3d
Create Date: 2026-07-22 14:50:03.326138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291b48396d89'
down_revision: Union[str, Sequence[str], None] = 'bb8f6e2a1c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comment', sa.String(length=16), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'comment')
    # ### end Alembic commands ###
