"""init auth service

Revision ID: bf42e0d31d92
Revises: 
Create Date: 2026-05-27 12:05:52.597130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf42e0d31d92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('is_test_user', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), server_default='USER', nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_yandex_sso',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('yandex_id', sa.BigInteger(), nullable=False),
    sa.Column('default_email', sa.String(length=64), nullable=False),
    sa.Column('default_avatar_id', sa.String(length=128), nullable=True),
    sa.Column('emails', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('yandex_id'))

    op.add_column('user', sa.Column('photo_url', sa.String(length=64), nullable=True))

    # ###end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_yandex_sso')
    op.drop_table('user')
    # ### end Alembic commands ###
